config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy] # searching for all routes, only specifies the necessary route
  # resources when you need /articles and then /articles/1 and etc (using REST)

  get 'signup', to: 'users#new'
  # post, patch, delete requests for users all in one, except the /signup route
  # because we already have our new controller used
  resources :users, except: [:new]

  # for login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # for categories
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ApplicationRecord # creating an articles table
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 10, maximum: 50 }
  validates :description, presence: true, length: { minimum: 20, maximum: 200}

  belongs_to :user
end



app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # means do before the particular action
  before_action :findArticle, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]

  def index
    # @article = Article.all
    @article = Article.paginate(page: params[:page], per_page: 10)
  end
  def show
    # @article = Article.find(params[:id])
    # thus, we can access a concrete article
    # like '.../articles/2' in URL, params is params, but also hashed, so id would be returned
    # in the hash format
  end

  def new
    # creating a new article

    # thus, we'll save the page from erroring NilClass when saving @article in db
    @article = Article.new
  end

  def edit
    # binding.break # to debug, look in the console, then use `params`, then `continue` in debug console
    # @article = Article.find(params[:id])
  end

  def create
    binding.break
    # displaying this article

    # when creating a new article, nothing might happen and a new article is not saved.
    # this is because we don't render it in `create` method in Articles controller.
    # by using render plain: params[:article], we'll specify what is going to be rendered: a new article.
    # so, on '/articles', a new article will be returned: {"title"=>"eweqweqwe", "description"=>"qweqeqweqwewqe"}
    # but, it only renders by the browser, the new article is NOT saved yet.

    # render plain: params[:article]

    # to save to db; :article is our db model
    # to redirect to /articles/id, use `rails routes --expanded`, find /articles/:id URI and method GET
    # PREFIX here is to access: article (which is a prefix)_path (which means path)
    # rails will
    # extract `id` from `@article` class instance.
    @article = Article.new(articleParams)
    binding.break
    # we'll set to a logged in user our article_id
    @article.user_id = current_user.id
    binding.break
    if @article.save!
      binding.break
      flash[:notice] = 'Article is created successfully.' # notice is the key
      redirect_to @article

    else
      # rendering form again: 'new' template
      # @article is available to 'new' template.
      # if you encounter 'NilClass problem', look:
      # the problem is, there is no @article on '/article/new', so we'll create
      # a new @article (which is empty) for the first time to prevent page from erroring:
      # look at new method
      render :new
    end

    puts @article

  end

  def update
    # binding.break
    # @article = Article.find(params[:id])
    if @article.update(articleParams)
      flash['notice'] = 'An article was updated successfully.'
      redirect_to @article

    else
      render :edit

    end
  end

  def destroy
    # binding.break
    # @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other # '/articles' page

  end

  # private # means that the module is only available to that controller
  def findArticle
    @article = Article.find(params[:id])
  end

  def articleParams
    params.require(:article).permit(:id, :title, :description, category_ids: [])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/views/articles/edit.html.erb
<h1> Editing the article </h1>

<% if @article.errors.any? %>
  <h1> The following errors prevented us from saving data in DB: </h1>
  <ul>
    <% @article.errors.full_messages.each do |err| %>
      <li> <%= err %> </li>
    <% end %>
  </ul>
<% end %>

<!-- in case of editing form, we want to display all existing info about the
article-->
<% if logged_in? && (@article.user_id == current_user.id || current_user.admin?) %>
  <%= form_with model: @article, method: :patch do |form|  %>
    <p>
      <%= form.label :title %> <br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :description %> <br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.submit "enter" %>
    </p>
  <% end %>
<% end %>

<%= link_to 'Return to the main page', articles_path %>


app/views/articles/index.html.erb
<div class="p-2">
  <p> <%= link_to 'About Page', about_path %> </p>
</div>

<div class="p-2">
  <p> <%= link_to 'The articles page', articles_path %> </p>
</div>

<% unless logged_in? %>
<div class="p-2">
      <p> <%=  link_to 'Log In', login_path  %> </p>
</div>
<%  end %>

<% if logged_in? && current_user %>
    <%= button_to "Log Out", logout_path,  method: :delete, data: { turbo_method: :delete }, class: "btn btn-outline-dark" %>
<% end  %>

<h1 class="h1--index p-4">The full listing of articles: </h1>

<div class="digg_pagination text-center m-4 pb-3">
  <div class="page_info">
    <%= page_entries_info @article %>
  </div>
  <%= will_paginate @article, :container => false %>
</div>

<div class="articles--table p-4">
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @article.each do |article| %>
      <tr>
        <td class="title"> <%= article.title %></td>
        <td class="desc"> <%= article.description %></td>
        <td> <%= link_to 'Show', article_path(article.id) %></td>

        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <td> <%= link_to 'Edit', edit_article_path(article.id) %></td>
            <td> <%= link_to 'Delete', article_path(article.id),  data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %> </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

  <% if logged_in? %>
      <p>
        <%= link_to 'Create a new article', new_article_path %>
      </p>
  <% end %>

</div>

<div class="gifcat--img">
  <img src="https://imgs.search.brave.com/HIOP_ok7rEDLaGTxvz6_6HRfkmXvHI9RTxMWIkzecHs/rs:fit:370:300:1/g:ce/aHR0cHM6Ly8zLmJw/LmJsb2dzcG90LmNv/bS8tZm0wQ2c1V0Zz/eTgvV0Y2WVdKeVV2/dUkvQUFBQUFBQUZv/ZjAvblJzcTNKTGZ3/TndQcVpBMjBmUERG/QUg4YU9VRkxIN25B/Q0xjQi9zMTYwMC9B/VzM1NjIzNF8wNC5n/aWY.gif"/>
</div>

app/views/articles/new.html.erb
<h1 class="h1--new--article">Creating a new article...</h1>

<!-- error displaying messages (when saving @article to db is unsuccessful) -->
<% if @article.errors.any? %>
  <h1> The following errors prevented us from saving data in DB: </h1>
  <ul>
    <% @article.errors.full_messages.each do |err| %>
      <li> <%= err %> </li>
    <% end %>
  </ul>
<% end %>

<!-- the form scope is a an article model, url and method included-->
<div class="pt-4">
  <%= form_with scope: :article, url: '/articles', method: :post, data: { turbo: false } do |form| %>

    <div class="p-2">
      <%= form.label :title %> <br>
      <%= form.text_field :title %>
    </div>

    <div class="p-2">
      <%= form.label :description %> <br>
      <%= form.text_area :description %>
    </div>

    <div class="p-2">
      <%= form.label :category %> <br>
      <%= form.collection_select :category_ids, Category.order(:name), :id, :name,
                                 {prompt: "Please Select a Category (can be empty)"}, {multiple: true}
                                   %>
    </div>

    <div class="p-2">
      <%= form.submit "enter" %>
    </div>


  <% end %>
</div>

app/views/articles/show.html.erb
<div class="p-4">
  <h1 class="showing-details">Showing details</h1>

  <div class="title">Title: <%= @article.title %></div>

  <div>
    <% if @article.categories.any? %>
      <%= render @article.categories %>
    <% end %>
  </div>

  <div class="description">Description: <%= @article.description %></div>

  <p>
    <% if logged_in? && (@article.user_id == current_user.id || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(@article), class: "" %>
      <%= button_to "Delete", article_path(@article),  method: :delete, data: { turbo_method: :delete }, class: "btn btn-outline-dark" %>
      <% end %>
    <%= link_to 'Return to the main page', root_path %>
</p>

</div>