config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy] # searching for all routes, only specifies the necessary route
  # resources when you need /articles and then /articles/1 and etc (using REST)

  get 'signup', to: 'users#new'
  # post, patch, delete requests for users all in one, except the /signup route
  # because we already have our new controller used
  resources :users, except: [:new]

  # for login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # for categories
  resources :categories, except: [:destroy]

end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25}
  validates :email, presence: true, uniqueness: true, length: { maximum: 105 }
  validates_format_of :email, with: /\w+@[a-z]+.[comnetorg]+/, message: "only characters are allowed after @"

  has_secure_password(validations: false)

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    #@user = User.all

    @user = User.paginate(page: params[:page], per_page: 10)
  end
  def new
    @user = User.new
  end

  def show
    findParams

    @article = @user.articles.paginate(page: params[:page], per_page: 10) # to show particular articles, connected to the user
  end

  def create
    @user = User.new(userPermit)
    #binding.break
    if @user.save!
      session[:user_id] = @user.id
      #binding.break
      redirect_to articles_path

    else
      render :new
    end

  end

  def edit
    findParams
  end

  def update
    findParams

    #binding.break
    if @user.update(userPermit)
      #binding.break
      flash['notice'] = "Your profile is successfully updated, #{@user.username}"
      redirect_to user_path(@user) # the same as @user

    else
      render :edit
    end
  end

  def destroy
    findParams
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account is successfully deleted!'
    redirect_to users_path
  end

  def findParams
    @user = User.find(params[:id])
  end
  def userPermit
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {size: 80})
    email_address = "valcat552@gmail.com"
    hash = Digest::MD5.hexdigest(email_address).downcase
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

    # we'll puts it in the img tag (the built-in method in RoR)
    image_tag(image_src, class: "rounded shadow mx-auto d-block", alt: user.username)
  end
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <h1> The following errors prevented us from saving data in DB: </h1>
  <ul>
    <% @user.errors.full_messages.each do |err| %>
      <li> <%= err %> </li>
    <% end %>
  </ul>
<% end %>

  <% unless logged_in? %>
  <<div class="p-3">
    <h1>Log in first.</h1>
    <p>
      <%= link_to 'Login', login_path %>
    </p>
  </div>

<%  end %>

<div class="p-2 m--1">
  <% if logged_in? && (@user.id != current_user.id && current_user.admin == false) %>
    <h1> Sorry, you are not permitted to edit this user.</h1>
    <p>
      <%= link_to 'Return to articles', articles_path %>
    </p>
    <p>
      <%= link_to 'Return to users', users_path %>
    </p>
    <p>
     <%= link_to 'Return to main page', root_path %>
    </p>
  <% end %>
</div>

<div class="p-2">
  <% if logged_in? && (@user.id == current_user.id || current_user.admin?) %>
    <h1> Editing the user </h1>
    <%= form_with model: @user, method: :patch do |form|  %>
      <p>
        <%= form.label :username %> <br>
        <%= form.text_field :username %>
      </p>

      <p>
        <%= form.label :email %> <br>
        <%= form.email_field :email %>
      </p>

      <p>
        <%= form.label :password %> <br>
        <%= form.password_field :password %>
      </p>

      <p>
        <%= form.submit(@user.new_record? ? 'Sign Up' : 'Update account')%>
      </p>
    <% end %>
  <% end %>
</div>



app/views/users/index.html.erb
<div class="digg_pagination text-center m-4 pb-3">

  <div class="page_info">
    <%= page_entries_info @user %>
  </div>
  <%= will_paginate @user, :container => false %>
</div>

<div class="text-center">
  <% @user.each do |user| %>

    <%= gravatar_for(user, size: 100) %>

    <p>
      <%= user.username %> : <%= mail_to user.email %>
    </p>

    <p class="text-primary fw-bold">
      Number of articles created: <%= user.articles.count %>
    </p>

    <div class="text-center pb-2">
      <%= link_to 'View the profile', user %> <!-- to the particular user profile -->
    </div>

      <% if logged_in? %>

      <% if user == current_user %>

        <div class="text-center pb-2">
          <%= link_to 'Edit the profile', edit_user_path(user) %>
        </div>
      <% end %>

      <% if current_user.admin? %>
        <div class="text-center">
          <%= button_to 'Delete user', user_path(user), method: :delete, data: {
            turbo_method: :delete,
            confirm: 'Do you want to delete the user?'
          }, class: "m-1 btn btn-outline-danger" %>
        </div>
        <% end %>

      <% end %>
  <% end %>
  </div>

<div class="mt-5 text-center">
  <p> <%= link_to 'Return to articles', articles_path  %> </p>
  <p> <%= link_to 'Return to about page', about_path  %> </p>
  <p> <%= link_to 'Return to the main page', root_path %> </p>
</div>

app/views/users/new.html.erb
<div class="p-3 user--registration">

  <h1 class="h1--new--user">Creating a new user...</h1>

  <%= form_with scope: :user, url: '/users', method: :post, data: { turbo: false } do |form| %>

    <p>
      <%= form.label :username %> <br>
      <%= form.text_field :username %>
    </p>

    <p>
      <%= form.label :email %> <br>
      <%= form.email_field :email %>
    </p>

    <p>
      <%= form.label :password %> <br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.submit "enter" %>
    </p>


  <% end %>

</div>

app/views/users/show.html.erb
<div class="p-4">
  <% if logged_in? && current_user == @user %>
    Logged in as <%= current_user.email %>
    <p></p>

    <%= "Admin" if current_user.admin? %>

    <p></p>

    <%= button_to "Log Out", logout_path,  method: :delete, data: { turbo_method: :delete }, class: "m-1 btn btn-outline-dark" %>
    <%= button_to "Delete account", user_path(current_user),  method: :delete, data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?" }, class: "m-1 btn btn-outline-danger" %>

    <% end %>

  <% unless logged_in? %>
    <%=  link_to "Sign Up", signup_path  %> or
    <%=  link_to "Log In", login_path  %>
  <%  end %>
</div>

  <div class=" dropdown-menu d-flex align-items-end flex-column" aria-labelledby="navbarDropdownMenuLink">
    <div class="dropdown-item p-2">
      <%= link_to 'Return to the articles page', articles_path %>
    </div>
    <div class="dropdown-item p-2">
      <%= link_to 'Return to the main page', root_path %>
    </div>
    <div class="dropdown-item p-2">
      <%= link_to 'Update the profile', edit_user_path(@user) %>
    </div>
  </div>

<div class="p-4">

  <%= gravatar_for @user, size: 200%>

  <div class="digg_pagination text-center m-4 pb-3">
    <div class="page_info">
      <%= page_entries_info @article %>
    </div>
    <%= will_paginate @article, :container => false %>
  </div>

  <h1 class="text-info"> All info about the person is here: </h1>
  <p class="text-muted"> Username: <%= @user.username %></p>
  <p class="font-weight-bold"> Email: <%= mail_to @user.email %></p>

  <p>All articles</p>
  <%= render 'layouts/partials/articles' %> <!--to display particular article, connected to the user-->


</div>