config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy] # searching for all routes, only specifies the necessary route
  # resources when you need /articles and then /articles/1 and etc (using REST)

  get 'signup', to: 'users#new'
  # post, patch, delete requests for users all in one, except the /signup route
  # because we already have our new controller used
  resources :users, except: [:new]

  # for login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # for categories
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categoryParams)
    binding.break
    # @category.user_id = current_user.id
    if @category.save
      binding.break
      flash[:notice] = 'A new category is created.'
      redirect_to @category

    else
      flash[:alert] = 'A new category is NOT created. Try again.'
      render :new
    end
  end

  def show
    findCategory
  end

  def edit
    findCategory
  end

  def update
    findCategory
    if @category.update(categoryParams)
      flash[:notice] = 'A category is updated'
      redirect_to @category

    else
      flash[:alert] = 'A category is not updated.'
      render :edit
    end

  end

  private
  def findCategory
    @category = Category.find(params[:id])
  end
  def categoryParams
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin
      flash[:alert] = 'Only admins are allowed to do that.'
      redirect_to categories_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div>
  <%= link_to category.name, categories_path(category) %>
</div>

app/views/categories/edit.html.erb
<div class="p-4">
  <%= form_with model: @category, method: :patch do |form|  %>
    <p>
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.submit "enter", class: 'btn btn-outline-dark' %>
    </p>
  <% end %>

<%= link_to 'Return to the articles page', articles_path %>

</div>

app/views/categories/index.html.erb
<h1 class="h1--index text-info p-4">The full listing of categories: </h1>

<div class="categories--table p-4">
  <table style="width:100%">
    <thead>
    <tr>
      <th>Name</th>
    </tr>
    </thead>

    <tbody>
    <% @category.each do |category| %>
      <tr>
        <td> <%= link_to category.name, category_path(category.id) %></td>
    <% end %>
    </tbody>
  </table>

  <div class="pt-3">
    <%= link_to 'Create a new category', new_category_path %>
  </div>

</div>

<div class="gifcat--img">
  <img src="https://imgs.search.brave.com/HIOP_ok7rEDLaGTxvz6_6HRfkmXvHI9RTxMWIkzecHs/rs:fit:370:300:1/g:ce/aHR0cHM6Ly8zLmJw/LmJsb2dzcG90LmNv/bS8tZm0wQ2c1V0Zz/eTgvV0Y2WVdKeVV2/dUkvQUFBQUFBQUZv/ZjAvblJzcTNKTGZ3/TndQcVpBMjBmUERG/QUg4YU9VRkxIN25B/Q0xjQi9zMTYwMC9B/VzM1NjIzNF8wNC5n/aWY.gif"/>
</div>

app/views/categories/new.html.erb
<% if logged_in? %>
  <div class="shadow-lg p-4 mb-4 bg-white">
    <h1 class="h1--index text-info">Create a category: </h1>
  </div>

  <div class="k p-4">
    <%= form_with scope: :category, url: '/categories', method: :post, data: { turbo: false } do |form| %>

      <p>
        <%= form.label :name %> <br>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.submit "Create a category", class: "btn btn-outline-dark"%>
      </p>


    <% end %>

  </div>

<% end %>

<% unless logged_in? %>
  <h1> Log in or sign in first...</h1>
<%   end %>

app/views/categories/show.html.erb
<div class="text-center m-4 pb-3">
  <h1 class="text-info"> <%= @category.name %>  category </h1>
</div>

<div class="text-center m-4 pb-3">
  <p> <%= link_to 'Edit category', edit_category_path(@category) %> </p>
  <p> <%= link_to 'Return to categories page', categories_path %> </p>
</div>